version: '3.9'

services:
  mongoDb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongoData:/data/db
      - mongoConfig:/data/configdb



volumes:
  mongoData:
  mongoConfig:


